### ISSUE TITLE
Fetching data failed!

### ISSUE THREAD

**Issue by pfreak2000** [paresy/Viessmann#8]
i got this error in ipsymcon

file_get_contents(https://api.viessmann.com/iot/v1/equipment/installations/253066/gateways/7571381708820209/devices/0/features/): failed to open stream: HTTP request failed! HTTP/1.1 502 Bad Gateway

 in C:\ProgramData\Symcon\modules\.store\de.paresy.viessmann\VitoConnect\module.php on line 267
Fetching data failed!

**Comment by paresy** [comment]
Normally this error means that the upstream server of Viessmann is not available at the moment. If the error persists you need to get a new token.

paresy

**Comment by pfreak2000** [comment]
my data was last retrieved in june. i have also reconnected the api without success

**Comment by paresy** [comment]
Can you double check if your developer account is active and your ClientID matches the one in your account?

**Comment by pfreak2000** [comment]
yes everything is active. i think viessmann may have changed something

**Comment by pfreak2000** [comment]
i got this if i go to uri url
Notice: Undefined index: code in C:\ProgramData\Symcon\modules\.store\de.paresy.viessmann\VitoConnect\module.php on line 141 invalid-token-request

**Comment by paresy** [comment]
This is expected. What happens if you go through the "Register" flow? Does it complete successfully?

**Comment by pfreak2000** [comment]
yes, I had this module now also already 2 years in use and only now I have these problems. I think the module is just totally outdated and no longer fits with the api together. I could my heating earlier also only read out but never control.

**Comment by paresy** [comment]
Can you send me a screenshot of your configuration? Viessmann updated their API sometime this year and this module was updated to cope with this fact. A lot of users are using this module, and it is working - therefore the problem needs to be on your end. Probably a configuration issue. If you say you are using it since 2 years, than yes - you probably missed the API change from Viessmann and are using the old version.

**Comment by pfreak2000** [comment]
Hast du Telegram  @cristmaster85

**Comment by paresy** [comment]
If you speak German please use our Community Forum: https://community.symcon.de/t/modul-viessmann-vitoconnect/48286/94

**Comment by pfreak2000** [comment]
i have done all this and had no success. you can't really do anything wrong. you set up the api and register ip symcon. that's all you can do.
